server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    username: 'postgres'
    url: jdbc:postgresql://192.168.21.153:5432/customer
    password: 'san_postgres'
  jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
      hibernate:
        ddl-auto: create-drop
      show-sql: 'true'