server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    username: 'postgres'
    url: jdbc:postgresql://192.168.21.153:5432/fraud
    password: 'san_postgres'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'